Name = "mainnet1"
Level = "info"
TokenExpiry = "168h0m0s"
Port = 1789
Host = "127.0.0.1"

[API]
  [API.GRPC]
    Hosts = [
      "vega-mainnet-data-grpc.commodum.io:443",
      "vega-grpc.mainnet.lovali.xyz:443",
      "vega-grpc.bharvest.io:3007",
      "vega-data.nodes.guru:3007",
      "grpc.velvet.tm.p2p.org:443",
      "rockaway.mainnet.vega.community:3007",
      "greenfield-one.mainnet.vega.community:3007",
      "grpc.vega.xprv.io:443",
      "vega.mainnet.stakingcabin.com:3007",
      "vega-mainnet.anyvalid.com:3002",
      "mainnet.vega.blockscope.net:3007",
      "grpcvega.gpvalidator.com:3007"
    ]
    Retries = 5
  [API.REST]
    Hosts = [
      "https://vega-mainnet-data-rest.commodum.io",
      "https://vega-rest.mainnet.lovali.xyz",
      "https://vega-rest.bharvest.io",
      "http://vega-data.nodes.guru:3009",
      "https://rest.velvet.tm.p2p.org:443",
      "http://rockaway.mainnet.vega.community:3009",
      "http://greenfield-one.mainnet.vega.community:3009",
      "http://vega.xprv.io/datanode",
      "http://vega.mainnet.stakingcabin.com:3009",
      "http://vega-mainnet.anyvalid.com:3003",
      "http://mainnet.vega.blockscope.net:3009",
      "http://restvega.gpvalidator.com:3009"
    ]
  [API.GraphQL]
    Hosts = [
      "https://vega-mainnet-data-graphql.commodum.io/query",
      "https://vega-query.mainnet.lovali.xyz/query",
      "https://vega-graphql.bharvest.io/query",
      "https://vega-data.nodes.guru:3008/query",
      "https://gql.velvet.tm.p2p.org:443/query",
      "http://rockaway.mainnet.vega.community:3008/query",
      "http://greenfield-one.mainnet.vega.community:3008/query",
      "https://vega.xprv.io/datanode/query",
      "https://vega.mainnet.stakingcabin.com/query",
      "http://mainnet.vega.blockscope.net:3008/query",
      "http://graphqlvega.gpvalidator.com:3008/query"
    ]

[Console]
  URL = ""
  LocalPort = 1847

[TokenDApp]
  URL = "token.vega.xyz"
  LocalPort = 1848
